export enum CleaningFrequency {
  Daily = 0,
  EveryThreeDays = 1,
  TwiceAWeek = 2,
  Weekly = 3,
  Fortnightly = 4,
  BiWeekly = 5,
  TwiceAMonth = 6,
  Monthly = 7,
  BiMonthly = 8,
  Quarterly = 9,
  Seasonally = 10,
  Yearly = 11,
  AsNeeded = 12,
}
